# Generated by Django 6.0.7 on 2026-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('essential', 'Besoins essentiels'), ('variable', 'Dépenses variables'), ('savings', 'Épargne')], default='variable', max_length=20),
        ),
    ]
